//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valt.UI.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class language {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Valt.UI.Lang.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        public static string ChangeCategoryTransactionTitle {
            get {
                return ResourceManager.GetString("ChangeCategoryTransactionTitle", resourceCulture);
            }
        }
        
        public static string CreateDatabaseTitle {
            get {
                return ResourceManager.GetString("CreateDatabaseTitle", resourceCulture);
            }
        }
        
        public static string CreateDatabase_TextLine1 {
            get {
                return ResourceManager.GetString("CreateDatabase.TextLine1", resourceCulture);
            }
        }
        
        public static string CreateDatabase_TextLine2 {
            get {
                return ResourceManager.GetString("CreateDatabase.TextLine2", resourceCulture);
            }
        }
        
        public static string CreateDatabase_TextLine3 {
            get {
                return ResourceManager.GetString("CreateDatabase.TextLine3", resourceCulture);
            }
        }
        
        public static string CreateDatabase_FilePath {
            get {
                return ResourceManager.GetString("CreateDatabase.FilePath", resourceCulture);
            }
        }
        
        public static string CreateDatabase_Password {
            get {
                return ResourceManager.GetString("CreateDatabase.Password", resourceCulture);
            }
        }
        
        public static string CreateDatabase_ConfirmPassword {
            get {
                return ResourceManager.GetString("CreateDatabase.ConfirmPassword", resourceCulture);
            }
        }
        
        public static string IconSelector_ClearSelection {
            get {
                return ResourceManager.GetString("IconSelector.ClearSelection", resourceCulture);
            }
        }
        
        public static string IconSelector_Color {
            get {
                return ResourceManager.GetString("IconSelector.Color", resourceCulture);
            }
        }
        
        public static string IconSelector_Loading {
            get {
                return ResourceManager.GetString("IconSelector.Loading", resourceCulture);
            }
        }
        
        public static string IconSelector_Title {
            get {
                return ResourceManager.GetString("IconSelector.Title", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        public static string InitialSelection_Title {
            get {
                return ResourceManager.GetString("InitialSelection.Title", resourceCulture);
            }
        }
        
        public static string InitialSelection_CreateOrLoadMessage {
            get {
                return ResourceManager.GetString("InitialSelection.CreateOrLoadMessage", resourceCulture);
            }
        }
        
        public static string InputPassword_DatabasePassword {
            get {
                return ResourceManager.GetString("InputPassword.DatabasePassword", resourceCulture);
            }
        }
        
        public static string InputPassword_Password {
            get {
                return ResourceManager.GetString("InputPassword.Password", resourceCulture);
            }
        }
        
        public static string ManageAccount_Title {
            get {
                return ResourceManager.GetString("ManageAccount.Title", resourceCulture);
            }
        }
        
        public static string ManageAccount_Name {
            get {
                return ResourceManager.GetString("ManageAccount.Name", resourceCulture);
            }
        }
        
        public static string ManageAccount_Icon {
            get {
                return ResourceManager.GetString("ManageAccount.Icon", resourceCulture);
            }
        }
        
        public static string ManageAccount_Visible {
            get {
                return ResourceManager.GetString("ManageAccount.Visible", resourceCulture);
            }
        }
        
        public static string ManageAccount_AccountType {
            get {
                return ResourceManager.GetString("ManageAccount.AccountType", resourceCulture);
            }
        }
        
        public static string ManageAccount_Currency {
            get {
                return ResourceManager.GetString("ManageAccount.Currency", resourceCulture);
            }
        }
        
        public static string ManageAccount_InitialAmount {
            get {
                return ResourceManager.GetString("ManageAccount.InitialAmount", resourceCulture);
            }
        }
        
        public static string ManageCategories_Title {
            get {
                return ResourceManager.GetString("ManageCategories.Title", resourceCulture);
            }
        }
        
        public static string ManageCategories_Name {
            get {
                return ResourceManager.GetString("ManageCategories.Name", resourceCulture);
            }
        }
        
        public static string ManageCategories_Icon {
            get {
                return ResourceManager.GetString("ManageCategories.Icon", resourceCulture);
            }
        }
        
        public static string ManageCategories_Delete {
            get {
                return ResourceManager.GetString("ManageCategories.Delete", resourceCulture);
            }
        }
        
        public static string ManageCategories_Tip {
            get {
                return ResourceManager.GetString("ManageCategories.Tip", resourceCulture);
            }
        }
        
        public static string ManageTransactions_Debt {
            get {
                return ResourceManager.GetString("ManageTransactions.Debt", resourceCulture);
            }
        }
        
        public static string ManageTransactions_Credit {
            get {
                return ResourceManager.GetString("ManageTransactions.Credit", resourceCulture);
            }
        }
        
        public static string ManageTransactions_Transfer {
            get {
                return ResourceManager.GetString("ManageTransactions.Transfer", resourceCulture);
            }
        }
        
        public static string ManageTransactions_Name {
            get {
                return ResourceManager.GetString("ManageTransactions.Name", resourceCulture);
            }
        }
        
        public static string ManageTransactions_Category {
            get {
                return ResourceManager.GetString("ManageTransactions.Category", resourceCulture);
            }
        }
        
        public static string ManageTransactions_From {
            get {
                return ResourceManager.GetString("ManageTransactions.From", resourceCulture);
            }
        }
        
        public static string ManageTransactions_Amount {
            get {
                return ResourceManager.GetString("ManageTransactions.Amount", resourceCulture);
            }
        }
        
        public static string ManageTransactions_To {
            get {
                return ResourceManager.GetString("ManageTransactions.To", resourceCulture);
            }
        }
        
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        public static string MathExpression_Title {
            get {
                return ResourceManager.GetString("MathExpression.Title", resourceCulture);
            }
        }
        
        public static string MathExpression_Description {
            get {
                return ResourceManager.GetString("MathExpression.Description", resourceCulture);
            }
        }
        
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings.Title", resourceCulture);
            }
        }
        
        public static string Settings_MainFiatCurrency {
            get {
                return ResourceManager.GetString("Settings.MainFiatCurrency", resourceCulture);
            }
        }
        
        public static string Settings_ShowHiddenAccounts {
            get {
                return ResourceManager.GetString("Settings.ShowHiddenAccounts", resourceCulture);
            }
        }
        
        public static string Settings_ClearAccountTotalsCache {
            get {
                return ResourceManager.GetString("Settings.ClearAccountTotalsCache", resourceCulture);
            }
        }
        
        public static string Settings_ClearTransactionTermCache {
            get {
                return ResourceManager.GetString("Settings.ClearTransactionTermCache", resourceCulture);
            }
        }
        
        public static string StatusDisplay_Title {
            get {
                return ResourceManager.GetString("StatusDisplay.Title", resourceCulture);
            }
        }
        
        public static string Transactions_Ratio {
            get {
                return ResourceManager.GetString("Transactions.Ratio", resourceCulture);
            }
        }
        
        public static string Transactions_TotalInFiat {
            get {
                return ResourceManager.GetString("Transactions.TotalInFiat", resourceCulture);
            }
        }
        
        public static string Transactions_Total {
            get {
                return ResourceManager.GetString("Transactions.Total", resourceCulture);
            }
        }
        
        public static string Transactions_ViewAllAccounts {
            get {
                return ResourceManager.GetString("Transactions.ViewAllAccounts", resourceCulture);
            }
        }
        
        public static string Transactions_Edit {
            get {
                return ResourceManager.GetString("Transactions.Edit", resourceCulture);
            }
        }
        
        public static string Transactions_Hide {
            get {
                return ResourceManager.GetString("Transactions.Hide", resourceCulture);
            }
        }
        
        public static string Transactions_Delete {
            get {
                return ResourceManager.GetString("Transactions.Delete", resourceCulture);
            }
        }
        
        public static string Transactions_MoveUp {
            get {
                return ResourceManager.GetString("Transactions.MoveUp", resourceCulture);
            }
        }
        
        public static string Transactions_MoveDown {
            get {
                return ResourceManager.GetString("Transactions.MoveDown", resourceCulture);
            }
        }
        
        public static string Transactions_EnterSearchTerm {
            get {
                return ResourceManager.GetString("Transactions.EnterSearchTerm", resourceCulture);
            }
        }
        
        public static string Transactions_AddTransaction {
            get {
                return ResourceManager.GetString("Transactions.AddTransaction", resourceCulture);
            }
        }
        
        public static string Transactions_Columns_Date {
            get {
                return ResourceManager.GetString("Transactions.Columns.Date", resourceCulture);
            }
        }
        
        public static string Transactions_Columns_Description {
            get {
                return ResourceManager.GetString("Transactions.Columns.Description", resourceCulture);
            }
        }
        
        public static string Transactions_Columns_Category {
            get {
                return ResourceManager.GetString("Transactions.Columns.Category", resourceCulture);
            }
        }
        
        public static string Transactions_Columns_OriginAccount {
            get {
                return ResourceManager.GetString("Transactions.Columns.OriginAccount", resourceCulture);
            }
        }
        
        public static string Transactions_Columns_TargetAccount {
            get {
                return ResourceManager.GetString("Transactions.Columns.TargetAccount", resourceCulture);
            }
        }
        
        public static string Transactions_Columns_Sats {
            get {
                return ResourceManager.GetString("Transactions.Columns.Sats", resourceCulture);
            }
        }
        
        public static string Transactions_Columns_SatsPriceToday {
            get {
                return ResourceManager.GetString("Transactions.Columns.SatsPriceToday", resourceCulture);
            }
        }
        
        public static string Transactions_Menu_Edit {
            get {
                return ResourceManager.GetString("Transactions.Menu.Edit", resourceCulture);
            }
        }
        
        public static string Transactions_Menu_Copy {
            get {
                return ResourceManager.GetString("Transactions.Menu.Copy", resourceCulture);
            }
        }
        
        public static string Transactions_Menu_RenameAll {
            get {
                return ResourceManager.GetString("Transactions.Menu.RenameAll", resourceCulture);
            }
        }
        
        public static string Transactions_Menu_Delete {
            get {
                return ResourceManager.GetString("Transactions.Menu.Delete", resourceCulture);
            }
        }
        
        public static string Main_Transactions {
            get {
                return ResourceManager.GetString("Main.Transactions", resourceCulture);
            }
        }
        
        public static string Main_Reports {
            get {
                return ResourceManager.GetString("Main.Reports", resourceCulture);
            }
        }
        
        public static string Main_Menu {
            get {
                return ResourceManager.GetString("Main.Menu", resourceCulture);
            }
        }
        
        public static string Main_Menu_Categories {
            get {
                return ResourceManager.GetString("Main.Menu.Categories", resourceCulture);
            }
        }
        
        public static string Main_Menu_Settings {
            get {
                return ResourceManager.GetString("Main.Menu.Settings", resourceCulture);
            }
        }
        
        public static string Transactions_MyStack {
            get {
                return ResourceManager.GetString("Transactions.MyStack", resourceCulture);
            }
        }
        
        public static string Transactions_MyOther {
            get {
                return ResourceManager.GetString("Transactions.MyOther", resourceCulture);
            }
        }
        
        public static string ManageTransactions_SelectToday {
            get {
                return ResourceManager.GetString("ManageTransactions.SelectToday", resourceCulture);
            }
        }
        
        public static string ManageTransactions_AddTitle {
            get {
                return ResourceManager.GetString("ManageTransactions.AddTitle", resourceCulture);
            }
        }
        
        public static string ManageTransactions_EditTitle {
            get {
                return ResourceManager.GetString("ManageTransactions.EditTitle", resourceCulture);
            }
        }
        
        public static string ManageTransactions_CopyTitle {
            get {
                return ResourceManager.GetString("ManageTransactions.CopyTitle", resourceCulture);
            }
        }
        
        public static string Settings_Culture {
            get {
                return ResourceManager.GetString("Settings.Culture", resourceCulture);
            }
        }
        
        public static string ManageCategories_RemoveFromGroup {
            get {
                return ResourceManager.GetString("ManageCategories.RemoveFromGroup", resourceCulture);
            }
        }
        
        public static string ManageTransactions_FixedExpense {
            get {
                return ResourceManager.GetString("ManageTransactions.FixedExpense", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_Title {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.Title", resourceCulture);
            }
        }
        
        public static string FixedExpenses_Columns_Name {
            get {
                return ResourceManager.GetString("FixedExpenses.Columns.Name", resourceCulture);
            }
        }
        
        public static string FixedExpenses_Columns_Category {
            get {
                return ResourceManager.GetString("FixedExpenses.Columns.Category", resourceCulture);
            }
        }
        
        public static string FixedExpenses_Columns_DefaultAccount {
            get {
                return ResourceManager.GetString("FixedExpenses.Columns.DefaultAccount", resourceCulture);
            }
        }
        
        public static string FixedExpenses_Columns_Currency {
            get {
                return ResourceManager.GetString("FixedExpenses.Columns.Currency", resourceCulture);
            }
        }
        
        public static string FixedExpenses_Columns_AmountType {
            get {
                return ResourceManager.GetString("FixedExpenses.Columns.AmountType", resourceCulture);
            }
        }
        
        public static string FixedExpenses_Columns_FixedAmount {
            get {
                return ResourceManager.GetString("FixedExpenses.Columns.FixedAmount", resourceCulture);
            }
        }
        
        public static string FixedExpenses_Columns_RangedAmountMin {
            get {
                return ResourceManager.GetString("FixedExpenses.Columns.RangedAmountMin", resourceCulture);
            }
        }
        
        public static string FixedExpenses_Columns_RangedAmountMax {
            get {
                return ResourceManager.GetString("FixedExpenses.Columns.RangedAmountMax", resourceCulture);
            }
        }
        
        public static string FixedExpenses_Columns_Period {
            get {
                return ResourceManager.GetString("FixedExpenses.Columns.Period", resourceCulture);
            }
        }
        
        public static string FixedExpenses_Columns_Day {
            get {
                return ResourceManager.GetString("FixedExpenses.Columns.Day", resourceCulture);
            }
        }
        
        public static string FixedExpenses_Columns_Enabled {
            get {
                return ResourceManager.GetString("FixedExpenses.Columns.Enabled", resourceCulture);
            }
        }
        
        public static string FixedExpenses_Columns_Amount {
            get {
                return ResourceManager.GetString("FixedExpenses.Columns.Amount", resourceCulture);
            }
        }
        
        public static string FixedExpenses_Period_Monthly {
            get {
                return ResourceManager.GetString("FixedExpenses.Period.Monthly", resourceCulture);
            }
        }
        
        public static string FixedExpenses_Period_Yearly {
            get {
                return ResourceManager.GetString("FixedExpenses.Period.Yearly", resourceCulture);
            }
        }
        
        public static string Transactions_ManageFixedExpenses {
            get {
                return ResourceManager.GetString("Transactions.ManageFixedExpenses", resourceCulture);
            }
        }
        
        public static string FixedExpensesEditor_EditTitle {
            get {
                return ResourceManager.GetString("FixedExpensesEditor.EditTitle", resourceCulture);
            }
        }
        
        public static string FixedExpensesEditor_AddTitle {
            get {
                return ResourceManager.GetString("FixedExpensesEditor.AddTitle", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_Name {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.Name", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_Category {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.Category", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_CurrencyDefinition {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.CurrencyDefinition", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_CurrencyDefinition_AttachedToDefaultAccount {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.CurrencyDefinition.AttachedToDefaultAccount", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_CurrencyDefinition_AttachedToCurrency {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.CurrencyDefinition.AttachedToCurrency", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_DefaultAccount {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.DefaultAccount", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_Currency {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.Currency", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_AmountDefinition {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.AmountDefinition", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_AmountDefinition_Fixed {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.AmountDefinition.Fixed", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_AmountDefinition_Variable {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.AmountDefinition.Variable", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_AmountDefinition_Hint {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.AmountDefinition.Hint", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_Amount_Fixed {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.Amount.Fixed", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_Amount_From {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.Amount.From", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_Amount_To {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.Amount.To", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_PeriodRange {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.PeriodRange", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_PeriodRange_Monthly {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.PeriodRange.Monthly", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_PeriodRange_Yearly {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.PeriodRange.Yearly", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_Day {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.Day", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_StartPeriod {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.StartPeriod", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_Enabled {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.Enabled", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_CurrencyMode {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.CurrencyMode", resourceCulture);
            }
        }
        
        public static string FixedExpenseEditor_Validation_DefaultAccountRequired {
            get {
                return ResourceManager.GetString("FixedExpenseEditor.Validation.DefaultAccountRequired", resourceCulture);
            }
        }
        
        public static string FixedExpenseEditor_Validation_CurrencyRequired {
            get {
                return ResourceManager.GetString("FixedExpenseEditor.Validation.CurrencyRequired", resourceCulture);
            }
        }
        
        public static string FixedExpenseEditor_Validation_FixedAmountRequired {
            get {
                return ResourceManager.GetString("FixedExpenseEditor.Validation.FixedAmountRequired", resourceCulture);
            }
        }
        
        public static string FixedExpenseEditor_Validation_RangedAmountMinRequired {
            get {
                return ResourceManager.GetString("FixedExpenseEditor.Validation.RangedAmountMinRequired", resourceCulture);
            }
        }
        
        public static string FixedExpenseEditor_Validation_RangedAmountMaxRequired {
            get {
                return ResourceManager.GetString("FixedExpenseEditor.Validation.RangedAmountMaxRequired", resourceCulture);
            }
        }
        
        public static string FixedExpenseEditor_Validation_InvalidRangedAmountMinMax {
            get {
                return ResourceManager.GetString("FixedExpenseEditor.Validation.InvalidRangedAmountMinMax", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_Delete_Alert {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.Delete.Alert", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_Delete_Message {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.Delete.Message", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_MonthlyExpenses {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.MonthlyExpenses", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_YearlyExpenses {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.YearlyExpenses", resourceCulture);
            }
        }
        
        public static string Transactions_Columns_Amount {
            get {
                return ResourceManager.GetString("Transactions.Columns.Amount", resourceCulture);
            }
        }
        
        public static string Transactions_Menu_BindToFixedExpenseCaption {
            get {
                return ResourceManager.GetString("Transactions.Menu.BindToFixedExpenseCaption", resourceCulture);
            }
        }
        
        public static string Transactions_Menu_UnbindToFixedExpenseCaption {
            get {
                return ResourceManager.GetString("Transactions.Menu.UnbindToFixedExpenseCaption", resourceCulture);
            }
        }
        
        public static string ManageTransactions_Properties_BoundToFixedExpense {
            get {
                return ResourceManager.GetString("ManageTransactions.Properties.BoundToFixedExpense", resourceCulture);
            }
        }
        
        public static string TransactionFixedExpenses_AddTransaction {
            get {
                return ResourceManager.GetString("TransactionFixedExpenses.AddTransaction", resourceCulture);
            }
        }
        
        public static string TransactionFixedExpenses_EditTransaction {
            get {
                return ResourceManager.GetString("TransactionFixedExpenses.EditTransaction", resourceCulture);
            }
        }
        
        public static string TransactionFixedExpenses_IgnoreForThisMonth {
            get {
                return ResourceManager.GetString("TransactionFixedExpenses.IgnoreForThisMonth", resourceCulture);
            }
        }
        
        public static string TransactionFixedExpenses_MarkAsPaid {
            get {
                return ResourceManager.GetString("TransactionFixedExpenses.MarkAsPaid", resourceCulture);
            }
        }
        
        public static string TransactionFixedExpenses_UndoIgnoreForThisMonth {
            get {
                return ResourceManager.GetString("TransactionFixedExpenses.UndoIgnoreForThisMonth", resourceCulture);
            }
        }
        
        public static string TransactionFixedExpenses_UndoMarkAsPaid {
            get {
                return ResourceManager.GetString("TransactionFixedExpenses.UndoMarkAsPaid", resourceCulture);
            }
        }
        
        public static string TransactionFixedExpenses_AddOrEditTransaction {
            get {
                return ResourceManager.GetString("TransactionFixedExpenses.AddOrEditTransaction", resourceCulture);
            }
        }
        
        public static string FixedExpenseEditor_Validation_InvalidRangePeriodStart {
            get {
                return ResourceManager.GetString("FixedExpenseEditor.Validation.InvalidRangePeriodStart", resourceCulture);
            }
        }
        
        public static string FixedExpenses_Period_Weekly {
            get {
                return ResourceManager.GetString("FixedExpenses.Period.Weekly", resourceCulture);
            }
        }
        
        public static string FixedExpenses_Period_Biweekly {
            get {
                return ResourceManager.GetString("FixedExpenses.Period.Biweekly", resourceCulture);
            }
        }
        
        public static string DaysOfWeek_Sunday {
            get {
                return ResourceManager.GetString("DaysOfWeek.Sunday", resourceCulture);
            }
        }
        
        public static string DaysOfWeek_Monday {
            get {
                return ResourceManager.GetString("DaysOfWeek.Monday", resourceCulture);
            }
        }
        
        public static string DaysOfWeek_Tuesday {
            get {
                return ResourceManager.GetString("DaysOfWeek.Tuesday", resourceCulture);
            }
        }
        
        public static string DaysOfWeek_Wednesday {
            get {
                return ResourceManager.GetString("DaysOfWeek.Wednesday", resourceCulture);
            }
        }
        
        public static string DaysOfWeek_Thursday {
            get {
                return ResourceManager.GetString("DaysOfWeek.Thursday", resourceCulture);
            }
        }
        
        public static string DaysOfWeek_Friday {
            get {
                return ResourceManager.GetString("DaysOfWeek.Friday", resourceCulture);
            }
        }
        
        public static string DaysOfWeek_Saturday {
            get {
                return ResourceManager.GetString("DaysOfWeek.Saturday", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_DayOfWeek {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.DayOfWeek", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_PeriodRange_Weekly {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.PeriodRange.Weekly", resourceCulture);
            }
        }
        
        public static string ManageFixedExpenses_PeriodRange_Biweekly {
            get {
                return ResourceManager.GetString("ManageFixedExpenses.PeriodRange.Biweekly", resourceCulture);
            }
        }
        
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        public static string ManageTransactions_Properties_PriceInSats {
            get {
                return ResourceManager.GetString("ManageTransactions.Properties.PriceInSats", resourceCulture);
            }
        }
        
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        public static string ChangePassword_OldPassword {
            get {
                return ResourceManager.GetString("ChangePassword.OldPassword", resourceCulture);
            }
        }
        
        public static string ChangePassword_Password {
            get {
                return ResourceManager.GetString("ChangePassword.Password", resourceCulture);
            }
        }
        
        public static string ChangePassword_ConfirmPassword {
            get {
                return ResourceManager.GetString("ChangePassword.ConfirmPassword", resourceCulture);
            }
        }
        
        public static string Settings_ChangeDatabasePassword {
            get {
                return ResourceManager.GetString("Settings.ChangeDatabasePassword", resourceCulture);
            }
        }
        
        public static string ChangePassword_TextLine1 {
            get {
                return ResourceManager.GetString("ChangePassword.TextLine1", resourceCulture);
            }
        }
        
        public static string RemainingFixedExpenses_Title {
            get {
                return ResourceManager.GetString("RemainingFixedExpenses.Title", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        public static string InstallPriceDatabase_Title {
            get {
                return ResourceManager.GetString("InstallPriceDatabase.Title", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string InstallPriceDatabase_Error_Title {
            get {
                return ResourceManager.GetString("InstallPriceDatabase.Error.Title", resourceCulture);
            }
        }
        
        public static string InstallPriceDatabase_Error_Info {
            get {
                return ResourceManager.GetString("InstallPriceDatabase.Error.Info", resourceCulture);
            }
        }
        
        public static string InstallPriceDatabase_Info {
            get {
                return ResourceManager.GetString("InstallPriceDatabase.Info", resourceCulture);
            }
        }
        
        public static string ValtFile_Error {
            get {
                return ResourceManager.GetString("ValtFile.Error", resourceCulture);
            }
        }
        
        public static string ValtPriceFile_Error {
            get {
                return ResourceManager.GetString("ValtPriceFile.Error", resourceCulture);
            }
        }
        
        public static string InstallingBitcoinPriceMessage {
            get {
                return ResourceManager.GetString("InstallingBitcoinPriceMessage", resourceCulture);
            }
        }
        
        public static string InstallingFiatPriceMessage {
            get {
                return ResourceManager.GetString("InstallingFiatPriceMessage", resourceCulture);
            }
        }
        
        public static string Transactions_Columns_Sats_Hint {
            get {
                return ResourceManager.GetString("Transactions.Columns.Sats.Hint", resourceCulture);
            }
        }
        
        public static string Transactions_Columns_SatsPriceToday_Hint {
            get {
                return ResourceManager.GetString("Transactions.Columns.SatsPriceToday.Hint", resourceCulture);
            }
        }
    }
}
